name: Build macOS DMG

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Homebrew dependencies
      run: |
        brew install ffmpeg create-dmg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests musicbrainzngs yt-dlp mutagen pyinstaller

    - name: Find ffmpeg path
      id: ffmpeg_path
      run: echo "path=$(which ffmpeg)" >> $GITHUB_OUTPUT

    - name: Build the application with PyInstaller
      env:
        MACOSX_DEPLOYMENT_TARGET: '10.9'
      run: |
        pyinstaller yoinker.py \
          --name Yoinker \
          --windowed \
          --add-binary "${{ steps.ffmpeg_path.outputs.path }}:." \
          --hidden-import "jaraco.text" \
          --noconfirm

    - name: Create DMG
      run: |
        create-dmg "dist/Yoinker.app"

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Yoinker-macOS-App
        path: Yoinker.dmg